(() => {
const D=window.ROADMAP_DATA,$=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const get=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}},set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const done=get('forgeDone',{}),notes=get('forgeNotes',{}),projectNotes=get('forgeProjectNotes',{});
let cal=new Date(),track='All',query='';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const local=s=>new Date(s+'T12:00:00'),iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const fmt=s=>local(s).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'});
const current=()=>{const t=iso(new Date());return D.weeks.find(w=>t>=w.start&&t<=w.end)||D.weeks[0]};
const wp=w=>{const n=w.steps.filter(x=>done[x.id]).length;return {n,total:w.steps.length,p:Math.round(n/w.steps.length*100)}};
const gp=()=>{const a=D.weeks.flatMap(w=>w.steps),n=a.filter(x=>done[x.id]).length;return {n,total:a.length,p:Math.round(n/a.length*100)}};
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function task(t,w){return `<label class="task ${done[t.id]?'done':''}"><input type="checkbox" data-task="${t.id}" ${done[t.id]?'checked':''}><span class="task-text">${esc(t.text)}</span><span class="hours">${t.hours}h</span></label>`}
function wireTasks(r=document){$$('[data-task]',r).forEach(x=>x.onchange=()=>{done[x.dataset.task]=x.checked;set('forgeDone',done);x.closest('.task')?.classList.toggle('done',x.checked);renderDash()})}
function renderDash(){const w=current(),g=gp(),p=wp(w),phase=D.phases.find(x=>x.id===w.phase);$('#dashboard').innerHTML=`
<div class="hero"><article class="card hero-main"><div class="kicker">${esc(D.profile.positioning)}</div><h2>Build a profile that is <span>hard to replace.</span></h2><p class="hero-copy">Learn → build → document → publish. Your university projects become proof that you understand both the physical system and the network/security layer.</p><div class="hero-meta"><span class="pill">${D.profile.weeklyCapacity}</span><span class="pill">Graduate ~${D.profile.graduationWindow}</span><span class="pill">GitHub @${D.profile.githubUser}</span></div></article>
<article class="card hero-side"><div><div class="kicker">ROADMAP PROGRESS</div><div class="progress-ring" style="--progress:${g.p}%"><div class="inside"><strong>${g.p}%</strong><span>${g.n}/${g.total} tasks</span></div></div></div><div class="stat-row"><div class="stat"><strong>${w.number}</strong><span>Current week</span></div><div class="stat"><strong>${p.p}%</strong><span>This week</span></div><div class="stat"><strong>${D.weeks.length}</strong><span>Total weeks</span></div></div></article></div>
<div class="section-head"><div><h2>This week — ${esc(w.topic)}</h2><p>${fmt(w.start)} → ${fmt(w.end)}</p></div><button class="small-btn" data-open="${w.number}">Open full week</button></div>
<article class="card week-card"><div class="week-top"><div><div class="kicker">WEEK ${w.number} · ${esc(w.track)}</div><h3>${esc(w.topic)}</h3><p>${esc(phase.goal)}</p></div><span class="phase-badge">${esc(w.phaseName)}</span></div><div class="task-list">${w.steps.map(x=>task(x,w)).join('')}</div><div class="deliverable"><strong>Deliverable:</strong> ${esc(w.deliverable)}</div></article>
<div class="section-head"><div><h2>18-month sequence</h2><p>We specialize after the fundamentals are reliable.</p></div></div><div class="phase-timeline">${D.phases.map((x,i)=>`<div class="phase-mini ${x.id===w.phase?'active':''}"><div class="num">0${i+1} · ${fmt(x.start)}</div><h4>${esc(x.name)}</h4><p>${esc(x.goal)}</p></div>`).join('')}</div>`;wireTasks($('#dashboard'));$$('[data-open]', $('#dashboard')).forEach(b=>b.onclick=()=>openWeek(+b.dataset.open))}
function renderCalendar(){const y=cal.getFullYear(),m=cal.getMonth(),first=new Date(y,m,1),idx=(first.getDay()+6)%7,start=new Date(y,m,1-idx);let cells='';for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const s=iso(d),events=D.weeks.filter(w=>w.start===s);cells+=`<div class="cal-day ${d.getMonth()!==m?'outside':''} ${s===iso(new Date())?'today':''}"><div class="day-num">${d.getDate()}</div>${events.map(w=>`<div class="cal-event" data-open="${w.number}">${esc(w.topic)}<span>Week ${w.number} · ${w.targetHours}h</span></div>`).join('')}</div>`}$('#calendar').innerHTML=`<div class="calendar-toolbar"><div><div class="kicker">INTERACTIVE PLAN</div><h2>${first.toLocaleDateString(undefined,{month:'long',year:'numeric'})}</h2></div><div class="calendar-nav"><button class="small-btn" id="prev">←</button><button class="small-btn" id="today">Today</button><button class="small-btn" id="next">→</button></div></div><div class="calendar-grid">${['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(x=>`<div class="weekday">${x}</div>`).join('')}${cells}</div><div class="section-head"><div><h2>How to use it</h2><p>Click a weekly event. Check tasks, save evidence, and generate a GitHub report.</p></div></div>`;$('#prev').onclick=()=>{cal=new Date(y,m-1,1);renderCalendar()};$('#next').onclick=()=>{cal=new Date(y,m+1,1);renderCalendar()};$('#today').onclick=()=>{cal=new Date();renderCalendar()};$$('[data-open]',$('#calendar')).forEach(x=>x.onclick=()=>openWeek(+x.dataset.open))}
function renderLearn(){const tracks=['All',...new Set(D.resources.map(x=>x.track))],list=D.resources.filter(x=>(track==='All'||x.track===track)&&(!query||`${x.title} ${x.description} ${x.track}`.toLowerCase().includes(query.toLowerCase())));$('#learn').innerHTML=`<div class="section-head"><div><h2>Learning library</h2><p>Official docs + good videos + hands-on labs. Don't just watch.</p></div><input id="search" class="search" placeholder="Search Python, Modbus, CCNA…" value="${esc(query)}"></div><div class="filters">${tracks.map(x=>`<button class="filter-chip ${x===track?'active':''}" data-track="${esc(x)}">${esc(x)}</button>`).join('')}</div><div class="resource-grid">${list.map(r=>`<article class="card resource"><div class="resource-top"><div class="kicker">${esc(r.kind)}</div><span class="tag">${esc(r.priority)}</span></div><h3>${esc(r.title)}</h3><p>${esc(r.description)}</p><div class="resource-actions"><a class="accent-btn" href="${r.url}" target="_blank" rel="noopener">Open resource ↗</a></div></article>`).join('')}</div>`;$('#search').oninput=e=>{query=e.target.value;renderLearn()};$$('[data-track]',$('#learn')).forEach(x=>x.onclick=()=>{track=x.dataset.track;renderLearn()})}
function renderProjects(){$('#projects').innerHTML=`<div class="section-head"><div><h2>Portfolio pipeline</h2><p>We reuse real mechatronics work instead of inventing filler projects.</p></div></div><div class="project-grid">${D.projects.map(p=>`<article class="card project-card"><div class="status-line"><div class="kicker">${esc(p.track)}</div><span class="status">${esc(p.status)}</span></div><h3>${esc(p.name)}</h3><p>${esc(p.summary)}</p><div class="project-columns"><div class="mini-list"><h4>Portfolio deliverables</h4><ul>${p.deliverables.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div><div class="mini-list"><h4>Security extension</h4><ul>${p.securityUpgrade.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div></div><div class="field" style="margin-top:12px"><label>Current notes / evidence</label><textarea data-project-note="${p.id}" placeholder="What did you actually build/test this week?">${esc(projectNotes[p.id]||'')}</textarea></div></article>`).join('')}</div>`;$$('[data-project-note]',$('#projects')).forEach(x=>x.onchange=()=>{projectNotes[x.dataset.projectNote]=x.value;set('forgeProjectNotes',projectNotes);toast('Project note saved')})}
function report(w){const p=wp(w),a=w.steps.filter(x=>done[x.id]),b=w.steps.filter(x=>!done[x.id]);return `# Forge Weekly Report — Week ${w.number}\n\n**Dates:** ${w.start} to ${w.end}\n**Phase:** ${w.phaseName}\n**Topic:** ${w.topic}\n**Progress:** ${p.n}/${p.total} (${p.p}%)\n\n## Completed\n${a.length?a.map(x=>`- [x] ${x.text}`).join('\n'):'- Nothing checked off yet.'}\n\n## Pending\n${b.length?b.map(x=>`- [ ] ${x.text}`).join('\n'):'- All tasks complete.'}\n\n## Deliverable\n${w.deliverable}\n\n## Notes / evidence\n${notes[w.number]||'_Add evidence here._'}\n`}
function renderGithub(){const w=current();$('#github').innerHTML=`<div class="github-layout"><div><div class="section-head"><div><h2>GitHub sync</h2><p>The connected repo is our source of truth for public portfolio evidence.</p></div></div><article class="card"><div class="kicker">CONNECTED REPOSITORY</div><h3 class="mono">Natequan/ot-cyber-roadmap</h3><p class="muted">When you tell me “sync my Forge progress”, I can update weekly reports and project docs through the connected GitHub account.</p><button class="accent-btn" id="genReport">Generate Week ${w.number} report</button></article><div class="section-head"><div><h2>Workflow</h2></div></div><div class="sync-steps"><div class="sync-step">Do the weekly lab and save evidence.</div><div class="sync-step">Check tasks and write notes inside Forge.</div><div class="sync-step">Generate the weekly report and paste it into our chat.</div><div class="sync-step">I update GitHub reports/project docs after reading the current repo.</div></div></div><div><div class="section-head"><div><h2>Repo structure</h2></div></div><div class="structure">ot-cyber-roadmap/\n├── index.html\n├── styles.css\n├── app.js\n├── data/roadmap.js\n├── projects/\n├── reports/\n└── .github/workflows/pages.yml</div></div></div>`;$('#genReport').onclick=()=>openReport(w.number)}
function openWeek(n){const w=D.weeks.find(x=>x.number===n),rs=w.resources.map(id=>D.resources.find(x=>x.id===id)).filter(Boolean);$('#weekDialogContent').innerHTML=`<div class="kicker">WEEK ${w.number} · ${fmt(w.start)} — ${fmt(w.end)}</div><h2>${esc(w.topic)}</h2><p class="muted">${esc(w.phaseName)} · ${w.targetHours}h target</p><div class="task-list">${w.steps.map(x=>task(x,w)).join('')}</div><div class="deliverable"><strong>Deliverable:</strong> ${esc(w.deliverable)}</div><div class="section-head"><div><h2>Resources</h2></div></div><div class="grid grid-2">${rs.map(r=>`<a class="card" target="_blank" rel="noopener" href="${r.url}"><div class="kicker">${esc(r.kind)}</div><h3 style="font-size:13px">${esc(r.title)}</h3><p class="muted" style="font-size:10px">${esc(r.description)}</p></a>`).join('')}</div><div class="field" style="margin-top:16px"><label>Week notes / evidence</label><textarea id="wn">${esc(notes[w.number]||'')}</textarea></div><div class="modal-actions"><button type="button" class="small-btn" id="saveNote">Save note</button><button type="button" class="accent-btn" id="makeReport">Generate GitHub report</button></div>`;wireTasks($('#weekDialogContent'));$('#saveNote').onclick=()=>{notes[w.number]=$('#wn').value;set('forgeNotes',notes);toast('Week note saved')};$('#makeReport').onclick=()=>{notes[w.number]=$('#wn').value;set('forgeNotes',notes);$('#weekDialog').close();openReport(w.number)};$('#weekDialog').showModal()}
function openReport(n){const w=D.weeks.find(x=>x.number===n),r=report(w);$('#reportDialogContent').innerHTML=`<div class="kicker">GITHUB SYNC PACKAGE</div><h2>Week ${w.number}: ${esc(w.topic)}</h2><p class="muted">Copy this report into our chat and say “sync my Forge progress”.</p><div class="report-preview">${esc(r)}</div><div class="modal-actions"><button type="button" class="accent-btn" id="copy">Copy report</button><button type="button" class="small-btn" id="download">Download .md</button></div>`;$('#copy').onclick=async()=>{await navigator.clipboard.writeText(r);toast('Report copied')};$('#download').onclick=()=>{const b=new Blob([r],{type:'text/markdown'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`forge-week-${String(w.number).padStart(2,'0')}.md`;a.click()};$('#reportDialog').showModal()}
function view(v){$$('.view').forEach(x=>x.classList.toggle('active',x.id===v));$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$('#viewTitle').textContent={dashboard:'Dashboard',calendar:'Calendar',learn:'Learning Library',projects:'Project Portfolio',github:'GitHub Sync'}[v];$('#sidebar').classList.remove('open');({dashboard:renderDash,calendar:renderCalendar,learn:renderLearn,projects:renderProjects,github:renderGithub}[v])()}
$$('.nav-item').forEach(x=>x.onclick=()=>view(x.dataset.view));$('#mobileMenu').onclick=()=>$('#sidebar').classList.toggle('open');$('#jumpToday').onclick=()=>{cal=new Date();view('calendar')};$('#quickReport').onclick=()=>openReport(current().number);$('#todayLabel').textContent=`${new Date().toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'}).toUpperCase()} · CAREER ROADMAP`;renderDash();
})();
