(() => {
const D=window.ROADMAP_DATA,$=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const get=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}},set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const done=get('forgeDone',{}),notes=get('forgeNotes',{}),projectNotes=get('forgeProjectNotes',{}),courseDone=get('nocturneCourseDone',{});
let cal=new Date(),track='All',query='';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const local=s=>new Date(s+'T12:00:00'),iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const fmt=s=>local(s).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'});
const current=()=>{const t=iso(new Date());return D.weeks.find(w=>t>=w.start&&t<=w.end)||D.weeks[0]};
const wp=w=>{const n=w.steps.filter(x=>done[x.id]).length;return {n,total:w.steps.length,p:Math.round(n/w.steps.length*100)}};
const gp=()=>{const a=D.weeks.flatMap(w=>w.steps),n=a.filter(x=>done[x.id]).length;return {n,total:a.length,p:Math.round(n/a.length*100)}};
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function task(t){return `<label class="task ${done[t.id]?'done':''}"><input type="checkbox" data-task="${t.id}" ${done[t.id]?'checked':''}><span class="task-text">${esc(t.text)}</span><span class="hours">${t.hours}h</span></label>`}
function wireTasks(r=document){$$('[data-task]',r).forEach(x=>x.onchange=()=>{done[x.dataset.task]=x.checked;set('forgeDone',done);x.closest('.task')?.classList.toggle('done',x.checked);renderDash();if($('#study').classList.contains('active'))renderStudy()})}

const topicChecks={
  'Network fundamentals':{lab:'Inspect your own Windows network configuration and trace one packet path.',verify:'You can point to your IPv4 address, subnet mask, gateway and MAC; explain ARP in one sentence; and show one ICMP Echo Request + Reply in Wireshark.',proof:'Screenshot of ipconfig + Wireshark ICMP capture + 5-line explanation.'},
  'Wireshark basics':{lab:'Capture ICMP, DNS, ARP and TCP from your own machine and isolate each with display filters.',verify:'For each protocol, identify source, destination and what the packet is doing. Save the capture as .pcapng.',proof:'One .pcapng + annotated screenshots or notes.'},
  'Python fundamentals':{lab:'Build a small device inventory CLI that stores name/IP pairs and prints them cleanly.',verify:'The script runs without syntax errors, accepts at least one user-entered device, and prints all devices.',proof:'device_inventory.py + terminal screenshot.'},
  'Git + GitHub':{lab:'Clone your roadmap repo, make one harmless documentation edit on a branch, commit it and push.',verify:'You can explain working tree → staging → commit → push and your commit is visible on GitHub.',proof:'Commit URL or screenshot + short README improvement.'},
  'IPv4 + subnetting':{lab:'Solve subnet problems and verify network, broadcast and host range.',verify:'Get at least 16/20 correct and explain one problem without a calculator.',proof:'Photo/PDF/text of 20 solved problems.'},
  'Switching':{lab:'Build a two-switch VLAN topology in Packet Tracer and verify same-VLAN reachability.',verify:'MAC tables populate correctly; same-VLAN hosts communicate; different VLANs do not without routing.',proof:'Packet Tracer file + screenshots of VLAN/MAC table.'},
  'Routing':{lab:'Build a small routed topology with two LANs and at least one router.',verify:'End hosts on different networks can ping after correct addressing and routes; traceroute path makes sense.',proof:'Packet Tracer file + routing table screenshot.'},
  'Python networking':{lab:'Write a network-status script that tests hosts and handles failures cleanly.',verify:'It distinguishes reachable/unreachable targets and does not crash on a bad address.',proof:'Python script + sample output.'},
  'Linux CLI':{lab:'Practice filesystem, permissions, processes and services on a Linux VM.',verify:'Complete your chosen command checklist plus at least five Bandit levels.',proof:'Command notes + Bandit level progress.'},
  'Linux networking':{lab:'Use ip, ss, ssh/curl and tcpdump to troubleshoot a simple connectivity scenario.',verify:'You can determine local IP, routes, listening sockets and capture one connection.',proof:'Troubleshooting note + tcpdump/Wireshark evidence.'},
  'Security fundamentals':{lab:'Complete guided introductory security labs and connect each concept to a real system.',verify:'Explain CIA, authn vs authz, hashing vs encryption and least privilege without notes.',proof:'Short concept sheet + lab completion evidence.'},
  'Modbus fundamentals':{lab:'Map coils/registers/function codes using the official Modbus data model.',verify:'Given a register-table row, you can state its data type, address and whether it is read/write.',proof:'One-page Modbus register-map cheat sheet.'},
  'Schneider lab inventory':{lab:'Record exact PLC/HMI or RS-485 device details and communication parameters from the real lab.',verify:'Model numbers, baud rate, parity, stop bits, slave ID and register table are all verified from device/software/docs.',proof:'Sanitized lab inventory committed to the project docs.'},
  'Python + Modbus':{lab:'Build a read-only Python client against your authorized isolated lab.',verify:'The script connects, reads approved registers, logs results and fails safely if the device is unavailable.',proof:'Script + terminal output + register mapping.'},
  'OT architecture':{lab:'Draw an OT network containing controller, HMI/SCADA, engineering station and enterprise boundary.',verify:'You can explain which communications are essential and where segmentation belongs.',proof:'Architecture/data-flow diagram.'}
};

function resourceById(id){return D.resources.find(x=>x.id===id)}
function courseGuide(w){
  if(w.number===1){
    return [
      {title:'Set up your tools',time:'45–60 min',what:'Get the five tools you need this week ready before studying anything else.',how:['Install or verify Git, VS Code, Python 3, Wireshark and Cisco Packet Tracer.','In Command Prompt run `python --version` and `git --version`.','Open Wireshark and confirm you can see your Wi-Fi/Ethernet interfaces.'],resources:['cisco-skills','packet-tracer','wireshark-learn','python-docs','git-book'],verify:'PASS when Python and Git print versions, Packet Tracer opens, and Wireshark lists a capture interface.',proof:'Keep one screenshot of the versions/tools if you want a clean Week 01 record.'},
      {title:'Read your own network',time:'60–75 min',what:'Learn IP, subnet mask, gateway, MAC and ARP using your laptop instead of only watching videos.',how:['Run `ipconfig /all` and identify IPv4 address, subnet mask, default gateway, DNS and physical address.','Run `arp -a` and locate your gateway or another local device.','Run `ping 8.8.8.8` and `tracert 8.8.8.8`.','Write one sentence explaining what each command showed you.'],resources:['cisco-skills','jeremy-ccna'],verify:'PASS when you can explain the difference between IP and MAC, what ARP resolves, and why the default gateway appears in your packet path.',proof:'Screenshot or text note containing the values you identified. Redact anything you do not want public.'},
      {title:'See packets in Wireshark',time:'45–60 min',what:'Turn networking theory into something visible.',how:['Start a capture on the active interface.','Run a ping, then filter with `icmp`. Identify Echo Request and Echo Reply.','Open a new website, then filter with `dns`. Find a query and response.','Click a packet and inspect source/destination IP plus the protocol fields.'],resources:['wireshark-learn'],verify:'PASS when you can show one request/reply pair and correctly identify source, destination and purpose.',proof:'Save one `.pcapng` or screenshot for your Week 01 evidence.'},
      {title:'Build a tiny Python tool',time:'60–90 min',what:'Use Python for an engineering/networking task from day one.',how:['Create `device_inventory.py`.','Start with a list of dictionaries containing device name and IP.','Print the inventory with a loop.','Add user input so a new device can be appended.','Optional: reject an empty device name or IP.'],resources:['python-docs','python-fcc'],verify:'PASS when the script runs from the terminal, accepts one new device and prints the full list without errors.',proof:'`device_inventory.py` + terminal screenshot.'},
      {title:'Collect the Schneider lab facts',time:'30–60 min',what:'Turn your university lab into the first OT portfolio project.',how:['Record the exact Schneider PLC model.','Record the HMI/RS-485 device model.','Record baud rate, parity, stop bits and Modbus slave ID.','Get or photograph the Modbus register/variable table.','Note the software used to configure the PLC/device.'],resources:['modbus'],verify:'PASS only when the values come from the real device/configuration/manual — do not guess missing parameters.',proof:'Sanitized notes or photos that we can later turn into `projects/schneider-modbus-lab.md`.'},
      {title:'Package the week',time:'30–45 min',what:'Finish with evidence, not just watched content.',how:['Check completed tasks in Nocturne.','Write what was clear, what was confusing and one thing to review.','Generate the weekly report.','Send me the report plus screenshots/code and say “Bro, sync Week 1.”'],resources:['git-book'],verify:'PASS when the deliverables actually exist and the report reflects what you did, not what you intended to do.',proof:'Week 01 report + code/captures/notes ready for GitHub.'}
    ];
  }
  const check=topicChecks[w.topic]||{lab:`Complete one focused hands-on exercise for ${w.topic}.`,verify:`You can explain the key idea without notes and the deliverable works as described.`,proof:w.deliverable};
  return [
    {title:'Learn the minimum',time:'~2h',what:`Understand the core idea: ${w.steps[0].text.replace(/^Learn:\s*/,'')}`,how:['Open the recommended resource(s) below.','Take only the notes needed to explain the concept in your own words.','Stop watching once you can start the lab; do not binge the entire course.'],resources:w.resources,verify:'PASS when you can give a 60-second explanation of the topic without reading your notes.',proof:'5–10 concise notes or a one-page cheat sheet.'},
    {title:'Do the lab',time:'~2.5h',what:check.lab,how:['Work only in your own lab, simulator, VM or explicitly authorized equipment.','Keep commands/configuration changes as you work.','If something fails, record the symptom and what fixed it.'],resources:w.resources,verify:check.verify,proof:check.proof},
    {title:'Check yourself',time:'~45–60 min',what:'Prove you understood what happened instead of only getting a result.',how:['Explain the result from memory.','Identify one failure mode and how you would troubleshoot it.','Repeat the key step once without following the guide line-by-line.'],resources:[],verify:`PASS when you can reproduce the important part and explain why it works. Main target: ${w.deliverable}`,proof:'A short “what I learned / what broke / how I verified it” note.'},
    {title:'Ship the evidence',time:'~45–60 min',what:'Turn the week into portfolio evidence.',how:['Save the useful screenshot, capture, script, config or diagram.','Remove passwords, secrets and sensitive university/company information.','Generate the weekly report and send it to me for GitHub sync.'],resources:['git-book'],verify:'PASS when another person could understand what you built from the evidence.',proof:w.deliverable}
  ];
}
function courseProgress(w){const g=courseGuide(w),n=g.filter((_,i)=>courseDone[`w${w.number}-c${i}`]).length;return {n,total:g.length,p:Math.round(n/g.length*100)}}

function renderDash(){const w=current(),g=gp(),p=wp(w),cp=courseProgress(w),phase=D.phases.find(x=>x.id===w.phase);$('#dashboard').innerHTML=`
<div class="hero"><article class="card hero-main"><div class="kicker">${esc(D.profile.positioning)}</div><h2>A calmer path to becoming <span>very hard to replace.</span></h2><p class="hero-copy">Each week is a small course: learn the minimum, do the lab, verify the result, then save proof. Your university work becomes a real portfolio instead of disappearing after the class ends.</p><div class="hero-meta"><span class="pill">${D.profile.weeklyCapacity}</span><span class="pill">Graduate ~${D.profile.graduationWindow}</span><span class="pill">GitHub @${D.profile.githubUser}</span></div></article>
<article class="card hero-side"><div><div class="kicker">TOTAL PROGRESS</div><div class="progress-ring" style="--progress:${g.p}%"><div class="inside"><strong>${g.p}%</strong><span>${g.n}/${g.total} tasks</span></div></div></div><div class="stat-row"><div class="stat"><strong>${w.number}</strong><span>week</span></div><div class="stat"><strong>${p.p}%</strong><span>tasks</span></div><div class="stat"><strong>${cp.p}%</strong><span>lesson</span></div></div></article></div>
<div class="section-head"><div><h2>Continue learning</h2><p>Your current Coursera-style module.</p></div></div>
<article class="card continue-card"><div><div class="kicker">WEEK ${w.number} · ${esc(w.track)}</div><h3>${esc(w.topic)}</h3><p>${fmt(w.start)} → ${fmt(w.end)} · ${w.targetHours}h target</p><div class="lesson-dots">${courseGuide(w).map((_,i)=>`<span class="lesson-dot ${courseDone[`w${w.number}-c${i}`]?'done':''}"></span>`).join('')}</div></div><div class="continue-actions"><button class="accent-btn" id="continueLesson">${cp.n? 'Continue':'Start'} lesson</button><button class="small-btn" data-open="${w.number}">Week details</button></div></article>
<div class="section-head"><div><h2>Weekly checklist</h2><p>These are the concrete outputs for the week.</p></div></div>
<article class="card week-card"><div class="week-top"><div><div class="kicker">WEEK ${w.number} · ${esc(w.track)}</div><h3>${esc(w.topic)}</h3><p>${esc(phase.goal)}</p></div><span class="phase-badge">${esc(w.phaseName)}</span></div><div class="task-list">${w.steps.map(task).join('')}</div><div class="deliverable"><strong>Deliverable:</strong> ${esc(w.deliverable)}</div></article>
<div class="section-head"><div><h2>The whole path</h2><p>Foundation first, specialization later.</p></div></div><div class="phase-timeline">${D.phases.map((x,i)=>`<div class="phase-mini ${x.id===w.phase?'active':''}"><div class="num">0${i+1} · ${fmt(x.start)}</div><h4>${esc(x.name)}</h4><p>${esc(x.goal)}</p></div>`).join('')}</div>`;
wireTasks($('#dashboard'));$('#continueLesson').onclick=()=>view('study');$$('[data-open]',$('#dashboard')).forEach(b=>b.onclick=()=>openWeek(+b.dataset.open))}

function renderStudy(){const w=current(),guide=courseGuide(w),cp=courseProgress(w),proofs=guide.map(x=>x.proof);$('#study').innerHTML=`<div class="study-shell"><div><article class="card study-intro"><div class="kicker">WEEK ${w.number} · GUIDED MODULE</div><h2>${esc(w.topic)}</h2><p>This is your step-by-step path. Each step tells you what to do, how to do it, where to learn it, and exactly what counts as a pass.</p><div class="course-progress"><span style="width:${cp.p}%"></span></div><p class="muted">${cp.n}/${cp.total} stages verified · ${cp.p}% complete</p></article><div class="course-list">${guide.map((s,i)=>{const key=`w${w.number}-c${i}`,complete=!!courseDone[key];const rs=(s.resources||[]).map(resourceById).filter(Boolean);return `<article class="course-step ${complete?'complete':''}"><div class="course-step-head"><div class="course-num">${complete?'✓':String(i+1).padStart(2,'0')}</div><div><h3>${esc(s.title)}</h3><p>${esc(s.time)} · ${esc(s.what)}</p></div><span class="phase-badge">${complete?'verified':'step '+(i+1)}</span></div><div class="course-step-body"><h4>HOW TO DO IT</h4><ul>${s.how.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>${rs.length?`<h4>LEARN / FOLLOW ALONG</h4><div class="course-resource-row">${rs.map(r=>`<a class="course-resource" target="_blank" rel="noopener" href="${r.url}">${esc(r.title)} ↗</a>`).join('')}</div>`:''}<div class="verify-box"><strong>Pass condition</strong><p>${esc(s.verify)}</p></div><label class="course-check"><input type="checkbox" data-course="${key}" ${complete?'checked':''}><span>I verified this step with real output/evidence.</span></label></div></article>`}).join('')}</div></div><aside class="study-side"><article class="card"><div class="kicker">WEEK PROOF</div><h3>What you should end up with</h3><ul class="proof-list">${proofs.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></article><article class="card"><div class="kicker">WHEN YOU GET STUCK</div><h3>Use me as your tutor</h3><p>Send the screenshot, code, command output or error. I can check the result against the current step instead of giving you another giant lecture.</p><button class="small-btn" id="studyReport">Generate report</button></article></aside></div>`;
$$('[data-course]',$('#study')).forEach(x=>x.onchange=()=>{courseDone[x.dataset.course]=x.checked;set('nocturneCourseDone',courseDone);renderStudy();renderDash()});$('#studyReport').onclick=()=>openReport(w.number)}

function renderCalendar(){const y=cal.getFullYear(),m=cal.getMonth(),first=new Date(y,m,1),idx=(first.getDay()+6)%7,start=new Date(y,m,1-idx);let cells='';for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const s=iso(d),events=D.weeks.filter(w=>w.start===s);cells+=`<div class="cal-day ${d.getMonth()!==m?'outside':''} ${s===iso(new Date())?'today':''}"><div class="day-num">${d.getDate()}</div>${events.map(w=>`<div class="cal-event" data-open="${w.number}">${esc(w.topic)}<span>Week ${w.number} · ${w.targetHours}h</span></div>`).join('')}</div>`}$('#calendar').innerHTML=`<div class="calendar-toolbar"><div><div class="kicker">STUDY CALENDAR</div><h2>${first.toLocaleDateString(undefined,{month:'long',year:'numeric'})}</h2></div><div class="calendar-nav"><button class="small-btn" id="prev">←</button><button class="small-btn" id="today">Today</button><button class="small-btn" id="next">→</button></div></div><div class="calendar-grid">${['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(x=>`<div class="weekday">${x}</div>`).join('')}${cells}</div><div class="section-head"><div><h2>Use it like a course calendar</h2><p>Open a week to see its checklist, or use Study for the detailed guided lesson.</p></div></div>`;$('#prev').onclick=()=>{cal=new Date(y,m-1,1);renderCalendar()};$('#next').onclick=()=>{cal=new Date(y,m+1,1);renderCalendar()};$('#today').onclick=()=>{cal=new Date();renderCalendar()};$$('[data-open]',$('#calendar')).forEach(x=>x.onclick=()=>openWeek(+x.dataset.open))}

function renderLearn(){const tracks=['All',...new Set(D.resources.map(x=>x.track))],list=D.resources.filter(x=>(track==='All'||x.track===track)&&(!query||`${x.title} ${x.description} ${x.track}`.toLowerCase().includes(query.toLowerCase())));$('#learn').innerHTML=`<div class="section-head"><div><h2>Resource library</h2><p>Official docs, good videos and hands-on labs. The Study page tells you when to use each one.</p></div><input id="search" class="search" placeholder="Search Python, Modbus, CCNA…" value="${esc(query)}"></div><div class="filters">${tracks.map(x=>`<button class="filter-chip ${x===track?'active':''}" data-track="${esc(x)}">${esc(x)}</button>`).join('')}</div><div class="resource-grid">${list.map(r=>`<article class="card resource"><div class="resource-top"><div class="kicker">${esc(r.kind)}</div><span class="tag">${esc(r.priority)}</span></div><h3>${esc(r.title)}</h3><p>${esc(r.description)}</p><div class="resource-actions"><a class="accent-btn" href="${r.url}" target="_blank" rel="noopener">Open ↗</a></div></article>`).join('')}</div>`;$('#search').oninput=e=>{query=e.target.value;renderLearn()};$$('[data-track]',$('#learn')).forEach(x=>x.onclick=()=>{track=x.dataset.track;renderLearn()})}

function renderProjects(){$('#projects').innerHTML=`<div class="section-head"><div><h2>Your project portfolio</h2><p>Real mechatronics projects, documented and extended toward security.</p></div></div><div class="project-grid">${D.projects.map(p=>`<article class="card project-card"><div class="status-line"><div class="kicker">${esc(p.track)}</div><span class="status">${esc(p.status)}</span></div><h3>${esc(p.name)}</h3><p>${esc(p.summary)}</p><div class="project-columns"><div class="mini-list"><h4>Portfolio proof</h4><ul>${p.deliverables.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div><div class="mini-list"><h4>Security extension</h4><ul>${p.securityUpgrade.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div></div><div class="field" style="margin-top:12px"><label>Current notes / evidence</label><textarea data-project-note="${p.id}" placeholder="What did you actually build or test?">${esc(projectNotes[p.id]||'')}</textarea></div></article>`).join('')}</div>`;$$('[data-project-note]',$('#projects')).forEach(x=>x.onchange=()=>{projectNotes[x.dataset.projectNote]=x.value;set('forgeProjectNotes',projectNotes);toast('Project note saved')})}

function report(w){const p=wp(w),cp=courseProgress(w),a=w.steps.filter(x=>done[x.id]),b=w.steps.filter(x=>!done[x.id]);return `# Nocturne Weekly Report — Week ${w.number}\n\n**Dates:** ${w.start} to ${w.end}\n**Phase:** ${w.phaseName}\n**Topic:** ${w.topic}\n**Checklist:** ${p.n}/${p.total} (${p.p}%)\n**Guided lesson:** ${cp.n}/${cp.total} (${cp.p}%)\n\n## Completed\n${a.length?a.map(x=>`- [x] ${x.text}`).join('\n'):'- Nothing checked off yet.'}\n\n## Pending\n${b.length?b.map(x=>`- [ ] ${x.text}`).join('\n'):'- All tasks complete.'}\n\n## Deliverable\n${w.deliverable}\n\n## Notes / evidence\n${notes[w.number]||'_Add evidence here._'}\n`}
function renderGithub(){const w=current();$('#github').innerHTML=`<div class="github-layout"><div><div class="section-head"><div><h2>Portfolio sync</h2><p>Your public evidence lives in GitHub; Nocturne is the study interface.</p></div></div><article class="card"><div class="kicker">CONNECTED REPOSITORY</div><h3 class="mono">Natequan/ot-cyber-roadmap</h3><p class="muted" style="font-size:10px;line-height:1.6">When you tell me “sync Week ${w.number}”, send the generated report plus your actual evidence. I can update the weekly report and project documentation through the connected GitHub account.</p><button class="accent-btn" id="genReport">Generate Week ${w.number} report</button></article><div class="section-head"><div><h2>Simple workflow</h2></div></div><div class="sync-steps"><div class="sync-step">Follow the guided lesson and produce the pass-condition evidence.</div><div class="sync-step">Check the completed stages and add your notes.</div><div class="sync-step">Generate the report and send it to me with screenshots/code.</div><div class="sync-step">I update the repo from the evidence you actually produced.</div></div></div><div><div class="section-head"><div><h2>Repo structure</h2></div></div><div class="structure">ot-cyber-roadmap/\n├── index.html\n├── styles.css\n├── app.js\n├── data/roadmap.js\n├── projects/\n├── reports/\n└── .github/workflows/pages.yml</div></div></div>`;$('#genReport').onclick=()=>openReport(w.number)}

function openWeek(n){const w=D.weeks.find(x=>x.number===n),rs=w.resources.map(resourceById).filter(Boolean),cp=courseProgress(w);$('#weekDialogContent').innerHTML=`<div class="kicker">WEEK ${w.number} · ${fmt(w.start)} — ${fmt(w.end)}</div><h2>${esc(w.topic)}</h2><p class="muted">${esc(w.phaseName)} · ${w.targetHours}h target · guided lesson ${cp.p}%</p><div class="task-list">${w.steps.map(task).join('')}</div><div class="deliverable"><strong>Deliverable:</strong> ${esc(w.deliverable)}</div><div class="section-head"><div><h2>Resources</h2></div></div><div class="grid grid-2">${rs.map(r=>`<a class="card" target="_blank" rel="noopener" href="${r.url}"><div class="kicker">${esc(r.kind)}</div><h3 style="font-family:var(--serif);font-size:17px">${esc(r.title)}</h3><p class="muted" style="font-size:9px">${esc(r.description)}</p></a>`).join('')}</div><div class="field" style="margin-top:16px"><label>Week notes / evidence</label><textarea id="wn">${esc(notes[w.number]||'')}</textarea></div><div class="modal-actions">${w.number===current().number?'<button type="button" class="accent-btn" id="goStudy">Open guided lesson</button>':''}<button type="button" class="small-btn" id="saveNote">Save note</button><button type="button" class="small-btn" id="makeReport">Generate report</button></div>`;wireTasks($('#weekDialogContent'));$('#saveNote').onclick=()=>{notes[w.number]=$('#wn').value;set('forgeNotes',notes);toast('Week note saved')};$('#makeReport').onclick=()=>{notes[w.number]=$('#wn').value;set('forgeNotes',notes);$('#weekDialog').close();openReport(w.number)};if($('#goStudy'))$('#goStudy').onclick=()=>{$('#weekDialog').close();view('study')};$('#weekDialog').showModal()}
function openReport(n){const w=D.weeks.find(x=>x.number===n),r=report(w);$('#reportDialogContent').innerHTML=`<div class="kicker">PORTFOLIO SYNC PACKAGE</div><h2>Week ${w.number}: ${esc(w.topic)}</h2><p class="muted">Copy this into our chat with your screenshots/code and say “Bro, sync Week ${w.number}.”</p><div class="report-preview">${esc(r)}</div><div class="modal-actions"><button type="button" class="accent-btn" id="copy">Copy report</button><button type="button" class="small-btn" id="download">Download .md</button></div>`;$('#copy').onclick=async()=>{await navigator.clipboard.writeText(r);toast('Report copied')};$('#download').onclick=()=>{const b=new Blob([r],{type:'text/markdown'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`nocturne-week-${String(w.number).padStart(2,'0')}.md`;a.click()};$('#reportDialog').showModal()}

function spotifyEmbedUrl(url){try{const u=new URL(url.trim());if(u.hostname!=='open.spotify.com')return null;const parts=u.pathname.split('/').filter(Boolean);if(parts.length<2)return null;const type=parts[0],id=parts[1],allowed=['playlist','album','track','artist','show','episode'];if(!allowed.includes(type)||!id)return null;return `https://open.spotify.com/embed/${type}/${id}?utm_source=generator&theme=0`}catch{return null}}
function loadSpotify(url,silent=false){const embed=spotifyEmbedUrl(url),box=$('#spotifyEmbed'),msg=$('#spotifyMessage');if(!embed){msg.textContent='Use a direct open.spotify.com playlist, album, track, show or episode link.';if(!silent)toast('Spotify link not recognized');return}msg.textContent='';box.classList.remove('empty-player');box.innerHTML=`<iframe title="Spotify Embed" src="${embed}" width="100%" height="152" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>`;set('nocturneSpotify',url);$('#spotifyUrl').value=url;if(!silent)toast('Spotify loaded')}
function initMusic(){const saved=get('nocturneSpotify','');if(saved)loadSpotify(saved,true);$('#spotifyLoad').onclick=()=>loadSpotify($('#spotifyUrl').value);$('#spotifyUrl').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();loadSpotify(e.currentTarget.value)}});$('#musicToggle').onclick=()=>$('#musicDock').classList.toggle('open');$('#musicClose').onclick=()=>$('#musicDock').classList.remove('open')}

function view(v){$$('.view').forEach(x=>x.classList.toggle('active',x.id===v));$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$('#viewTitle').textContent={dashboard:'Home',study:'Study',calendar:'Calendar',learn:'Resources',projects:'Projects',github:'Portfolio sync'}[v];$('#sidebar').classList.remove('open');({dashboard:renderDash,study:renderStudy,calendar:renderCalendar,learn:renderLearn,projects:renderProjects,github:renderGithub}[v])()}
$$('.nav-item').forEach(x=>x.onclick=()=>view(x.dataset.view));$('#mobileMenu').onclick=()=>$('#sidebar').classList.toggle('open');$('#jumpToday').onclick=()=>view('study');$('#quickReport').onclick=()=>openReport(current().number);$('#todayLabel').textContent=`${new Date().toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'}).toUpperCase()} · STUDY ROADMAP`;initMusic();renderDash();
})();
